### ISSUE TITLE
User is undefined

### ISSUE THREAD

**Issue by CASPERg267** [Assistants-Center/Discord-Dashboard#54]
**Describe the bug**
i am doing console.log for the results i get on the dashboard for testing.

**To Reproduce**
this is my code
https://sourceb.in/7iOVVr7Y0q
**Expected behavior**
getting an object full of user data (id - username - discriminator - voiceChannel)

**Screenshots**
![image](https://user-images.githubusercontent.com/74456381/172020143-f8b908ba-2b86-4079-aeb6-976888b6a892.png)

**Additional context**
last version of the module
discord.js: 13.7.0

**Comment by breftejk** [comment]
Thank you for reporting this issue. It's known already and I'll fix this as
soon as I will get better after accident.

Thanks for understanding and have a good morning/day/evening 🦊

**Comment by CASPERg267** [comment]
Oh so sorry bro to hear that, really didn't know that and i wish you to get well soon.

Also if you can make guild object gives all guild data not just guild id same goes for user
and thanks for this awesome module

**Comment by breftejk** [comment]
Fixed + added. Both guild and user has now `object` values.

DOCS: https://github.com/Assistants-Center/Discord-Dashboard-Docs/commit/41aa4882f9f8fe48b6e3930aa2dc1bf35de96695
