### ISSUE TITLE
The setNew returning null 

### ISSUE THREAD

**Issue by Naveenravi07** [Assistants-Center/Discord-Dashboard#57]
I am using DBD channelsSelect form  to get the channel .But the newData arg it returned null even though i selected a channel.  This is not only for the channelSelect form , i tried using the roleSelect form but it also returned null. I think the setNew function itself is not working for me .

Here is my page settings 

_settings: [
      {
        categoryId: "test",
        categoryName: "Welcome System",
        categoryDescription: "Customize the welcome message and much more here ",
        categoryOptionsList: [
          {
            optionid: "hey",
            optionName: "Welcome Channel",
            optionDescription: "Set Or Reset The Welcome Channel of the server",
            optionType: DBD.formTypes.channelsSelect(false, "GUILD_TEXT"),
            getActualSet: async ({ guild }) => {
              return welcomehannel[guild.id] || null;
            },
            setNew: async ({ guild, user, newData }) => {
              console.log(newData);
              welcomehannel[guild.id] = await newData;
              return;
            }
          }
        ]
      }
    ]_

**Comment by breftejk** [comment]
CNR, please make sure your d.js client has Guild Channels intent. Waiting for your reply.

**Comment by Naveenravi07** [comment]
it was my problem with some config ig. I rewrote the dashboard code completely and it worked
