### ISSUE TITLE
Ty betoniarzu.

### ISSUE THREAD

**Issue by TheLegendOfWolf** [Assistants-Center/Discord-Dashboard#64]
Dlaczego mnie wywalasz z teamu. To jest bardzo nieładne zachowanie. Dostałem prawie zawału, i nie dostałem ani przeprosin ani podziękowań za cudowne kontakty. Mój prawnik wystosuje dla Pana pozew. Widzimy się w sądzie ty betoniarzu ty.

**Comment by breftejk** [comment]
AAA! ooo! Dlaczego mnie wywalasz z teamu. To jest bardzo nieładne zachowanie. Dostałem prawie zawału, i nie dostałem ani przeprosin ani podziękowań za cudowne kontakty. Mój prawnik wystosuje dla Pana pozew. Widzimy się w sądzie ty betoniarzu ty.

**Comment by TheLegendOfWolf** [comment]
> AAA! ooo! Dlaczego mnie wywalasz z teamu. To jest bardzo nieładne zachowanie. Dostałem prawie zawału, i nie dostałem ani przeprosin ani podziękowań za cudowne kontakty. Mój prawnik wystosuje dla Pana pozew. Widzimy się w sądzie ty betoniarzu ty.


Ty chamie jeden, dlaczego kopiujesz moje komentarze. Będzie ban.

**Comment by breftejk** [comment]
g
